export const shops = [
  {
    id: 1,
    name: "Centella Ampoule",
    price: "24.0000",
    image: "/Centella Ampoule.png",
    whatitis: "This lightweight ampoule absorbs quickly into the skin, providing instant soothing relief and long-lasting hydration. Perfect for all skin types, especially sensitive and irritated skin.",
    Benefits:" lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    skintype:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    ingreditions: "Centella Asiatica Extract (100% from Madagascar), Purified Water, Glycerin, Butylene Glycol, 1,2-Hexanediol",
  },
  { id: 2, 
    name: "Centella Air-Fit Suncream Plus SPF50+ PA++++", 
    price: "336.000", 
    image: "/Centella Air-Fit Suncream Plus SPF50+ PA++++.png",
    whatitis: "This lightweight ampoule absorbs quickly into the skin, providing instant soothing relief and long-lasting hydration. Perfect for all skin types, especially sensitive and irritated skin.",
    Benefits:" lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    skintype:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    ingreditions: "Centella Asiatica Extract (100% from Madagascar), Purified Water, Glycerin, Butylene Glycol, 1,2-Hexanediol",
   },
  { id: 3, name: "Centella Soothing Cream", price: 340000.0, image: "/Centella Soothing Cream.png" },
  { id: 4, name: "Centella Toning Toner", price: 340000.0, image: "/Centella Toning Toner.png" },
  { id: 5, name: "Centella Ampoule Foam", price: 240000.0, image: "/Centella Ampoule Foam.png" },
  { id: 6, name: "Centella Light Cleansing Oil", price: 240000.0, image: "/Centella Light Cleansing Oil.png" },
  { id: 7, name: "Centella Cream", price: 2400000.0, image: "/Centella Cream.png" },
  { id: 8, name: "Centella Travel Kit", price: 240000.0, image: "/Centella Travel Kit.png" },
  { id: 9, name: "Centella Quick Calming Pad", price: 240000.0, image: "/Centella Quick Calming Pad.png" },
  { id: 10, name: "Centella Air-Fit Suncream Light SPF30 PA++++", price: 240000.0, image: "/Centella Air-Fit Suncream Light SPF30 PA++++.png" },
  { id: 11, name: "Skin Relief Duo", price: 240000.0, image: "/Skin Relief Duo.png" },
  { id: 12, name: "Double Cleansing Duo", price: 240000.0, image: "/Double Cleansing Duo.png" },
  { id: 13, name: "Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++", price: 240000.0, image: "/Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++.png" },
  { id: 14, name: "Hyalu-Cica Silky-Fit Sun Stick", price: 240000.0, image: "/Hyalu-Cica Silky-Fit Sun Stick.png" },
  { id: 15, name: "Hyalu-Cica Sleeping Pack", price: 240000.0, image: "/Hyalu-Cica Sleeping Pack.png" },
  { id: 16, name: "Hyalu-Cica Moisture Cream", price: 240000.0, image: "/Hyalu-Cica Moisture Cream.png" },
  { id: 17, name: "Hyalu-Cica Blue Serum", price: 240000.0, image: "/Hyalu-Cica Blue Serum.png" },
  { id: 18, name: "Hyalu-Cica First Ampoule", price: 240000.0, image: "/Hyalu-Cica First Ampoule.png" },
  { id: 19, name: "Hyalu-Cica Sunsational Kit", price: 240000.0, image: "/Hyalu-Cica Sunsational Kit.png" },
  { id: 20, name: "Hyalu-Cica Cloudy Mist", price: 240000.0, image: "/Hyalu-Cica Cloudy Mist.png" },
  { id: 21, name: "Hyalu-Cica GLOW 1004 DUO", price: 240000.0, image: "/GLOW 1004 DUO.png" },
  { id: 22, name: "Hyalu-Cica Gentle Cleansing Milk", price: 240000.0, image: "/Hyalu-Cica Gentle Cleansing Milk.png" },
  { id: 23, name: "Hyalu-Cica Jelly-Fit Ampoule Pad", price: 240000.0, image: "/Hyalu-Cica Jelly-Fit Ampoule Pad.png" },
  { id: 25, name: "Tone Brightening Capsule Ampoule", price: 240000.0, image: "/Tone Brightening Capsule Ampoule.png" },
  { id: 26, name: "Tone Brightening Cleansing Gel Foam", price: 240000.0, image: "/Tone Brightening Cleansing Gel Foam.png" },
  { id: 27, name: "Tone Brightening Boosting Toner", price: 240000.0, image: "/Tone Brightening Boosting Toner.png" },
  { id: 28, name: "Tone Brightening Capsule Cream", price: 240000.0, image: "/Tone Brightening Capsule Cream.png" },
  { id: 29, name: "Tone Brightening Tone-Up Sunscreen", price: 240000.0, image: "/Tone Brightening Tone-Up Sunscreen.png" },
  { id: 30, name: "Tone Brightening Dark Spot Ampoule Pad", price: 240000.0, image: "/Tone Brightening Dark Spot Ampoule Pad.png" },
  { id: 31, name: "Tone Brightening Set", price: 240000.0, image: "/Tone Brightening Set.png" },
  { id: 32, name: "Poremizing Quick Clay Stick Mask", price: 240000.0, image: "/Poremizing Quick Clay Stick Mask.png" },
  { id: 33, name: "Poremizing Fresh Ampoule", price: 240000.0, image: "/Poremizing Fresh Ampoule.png" },
  { id: 34, name: "Poremizing Deep Cleansing Foam", price: 240000.0, image: "/Poremizing Deep Cleansing Foam.png" },
  { id: 35, name: "Poremizing Clear Toner", price: 240000.0, image: "/Poremizing Clear Toner.png" },
  { id: 36, name: "Poremizing Light Gel Cream", price: 240000.0, image: "/Poremizing Light Gel Cream.png" },
  { id: 37, name: "Poremizing Velvet Finish Sunscreen", price: 240000.0, image: "/Poremizing Velvet Finish Sunscreen.png" },
  { id: 38, name: "Poremizing Perfect Pore Set", price: 240000.0, image: "/Perfect Pore Set.png" },
  { id: 39, name: "Tea-Trica Relief Ampoule", price: 240000.0, image: "/Tea-Trica Relief Ampoule.png" },
  { id: 40, name: "Tea-Trica Spot Cream", price: 240000.0, image: "/Tea-Trica Spot Cream.png" },
  { id: 41, name: "Tea-Trica BHA Foam", price: 240000.0, image: "/Tea-Trica BHA Foam.png" },
  { id: 42, name: "Tea-Trica B5 Cream", price: 240000.0, image: "/Tea-Trica B5 Cream.png" },
  { id: 43, name: "Tea-Trica Purifying Toner", price: 240000.0, image: "/Tea-Trica Purifying Toner.png" },
  { id: 44, name: "Tea-Trica Soothing Sun Milk", price: 240000.0, image: "/Tea-Trica Soothing Sun Milk.png" },
  { id: 45, name: "Tea-Trica Mild Peeling Gel", price: 240000.0, image: "/Tea-Trica Mild Peeling Gel.png" },
  { id: 46, name: "Tea-Trica Intensive Calming Set", price: 240000.0, image: "/Tea-Trica Intensive Calming Set.png" },
  { id: 47, name: "Probio-Cica Bakuchiol Eye Cream", price: 240000.0, image: "/Probio-Cica Bakuchiol Eye Cream.png" },
  { id: 48, name: "Probio-Cica Essence Toner", price: 240000.0, image: "/Probio-Cica Essence Toner.png" },
  { id: 49, name: "Probio-Cica Intensive Ampoule", price: 240000.0, image: "/Probio-Cica Intensive Ampoule.png" },
  { id: 50, name: "Probio-Cica Enrich Cream", price: 240000.0, image: "/Probio-Cica Enrich Cream.png" },
  { id: 51, name: "Probio-Cica GLOW 1004 DUO", price: 240000.0, image: "/Probio-Cica GLOW 1004 DUO.png" },
  { id: 52, name: "Probio-Cica Glow Sun Ampoule", price: 240000.0, image: "/Probio-Cica Glow Sun Ampoule.png" },
  { id: 53, name: "Probio-Cica Perfect Anti-Aging Routine Set", price: 240000.0, image: "/Perfect Anti-Aging Routine Set.png" }
];