import { Description } from "@radix-ui/react-toast";

export const shops = [
  {
    id: 1,
    name: "Centella Ampoule",
    price: "336.000",
    image: "/Centella Ampoule.png",
    whatitis: "An all-rounder ampoule formulated to help soothe visible redness and comfort sensitive-looking skin, featuring high quality Madagascan Centella Asiatica extract",
    Benefits: " Soothing, Hydrating.",
    ingreditions: "Centella Asiatica Extract",
    Description: "Signature Soothing Ampoule",
  },
  {
    id: 2,
    name: "Centella Air-Fit Suncream Plus SPF50+ PA++++",
    price: "275.000",
    image: "/Centella Air-Fit Suncream Plus SPF50+ PA++++.png",
    whatitis: "A lightweight physical sunscreen with a slight tint that blurs the skin and pores to a natural matte finish.",
    Benefits: "Calming, SPF",
    ingreditions: "Centella Asiatica Extract, Multi BSASM, Madecassoside",
    Description: "Beige Tinted Mineral sunscreen",
  },
  {
    id: 3,
    name: "Centella Soothing Cream",
    price: "127.000",
    image: "/Centella Soothing Cream.png",
    whatitis: "A non sticky soothing gel formulated with Centella, Trehalose, and Ceramide NP that moisturizes the skin and helps support the skin natural barrier.",
    Benefits: "Soothing, Hydrating",
    ingreditions: "Centella Asiatica Extract, Trehalose, Sodium Hyaluronate, Ceramide NP, Cholesterol",
    Description: "Non-sticky Soothing Gel Cream",
  },
  {
    id: 4,
    name: "Centella Toning Toner",
    price: "85.000",
    image: "/Centella Toning Toner.png",
    whatitis: "A gentle, PHA exfoliating toner designed for daily use to promote smoother-looking skin.",
    Benefits: "Soothing, Mild exfoliation",
    ingreditions: "Centella Asiatica Extract, Gluconolactone, Betaine",
    Description: "Mild Daily Exfoliating Toner",
  },
  {
    id: 5,
    name: "Centella Ampoule Foam",
    price: "68.000",
    image: "/Centella Ampoule Foam.png",
    whatitis: "A pH-balanced (pH 5) cleanser formulated with coconut-derived surfactants and citric acid that gently cleanses the skin without leaving it feeling dry or tight.",
    Benefits: "Soothing, Hydrating, Mild Exfoliation",
    ingreditions: "Normal, Sensitivity-prone skin",
    Description: "Low pH & Daily Foam Cleanser",
  },
  {
    id: 6,
    name: "Centella Light Cleansing Oil",
    price: "93.000",
    image: "/Centella Light Cleansing Oil.png",
    whatitis: "Centella and 6 plant-derived oils gently dissolve makeup, sunscreen and excess sebum on the skin, leaving a refreshing, oil-free finish.",
    Benefits: "Calming, Hydrating, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Helianthus Annuus (Sunflower) Seed Oil, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil",
    Description: "Light & Gentle Cleansing Oil",
  },
  {
    id: 7,
    name: "Centella Cream",
    price: "153.000",
    image: "/Centella Cream.png",
    whatitis: "A light cream formulated with Panthenol and TECA that soothes, moisturizes, and nourishes the skin.",
    Benefits: "Soothing, Hydrating",
    ingreditions: "Centella Asiatica Extract, Panthenol, TECA (Madecassoside, Asiaticoside, Madecassic Acid, Asiatic Acid)",
    Description: "Lightweight Moisturizing Cream",
  },
  {
    id: 8,
    name: "Centella Travel Kit",
    price: "375.000",
    image: "/Centella Travel Kit.png",
    whatitis: "A full Centella skincare routine set with 5 mini-sized products for travel or trial of the Centella line..",
    Benefits: "Calming, Hydrating, Mild exfoliating, Traveling Size",
    ingreditions:
      "Centella Asiatica Extract, Gluconolactone, Betaine, Citric Acid, Sodium Hyaluronate, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Helianthus Annuus (Sunflower) Seed Oil, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Trehalose, Ceramide NP, Cholesterol",
    Description: "100% Centella asiatica extract from the untouched nature of Madagascar",
  },
  {
    id: 9,
    name: "Centella Quick Calming Pad",
    price: "321.000",
    image: "/Centella Quick Calming Pad.png",
    whatitis: "An essence-rich toner pad with Centella and Panthenol soothes and hydrates the skin in a simple 2-minute step.",
    Benefits: "Calming, Hydrating",
    ingreditions: "Centella Asiatica Extract, Gluconolactone, Betaine",
    Description: "Centella Asiatica Extract, Panthenol, Sodium Hyaluronate",
  },
  {
    id: 10,
    name: "Centella Air-Fit Suncream Light SPF30 PA++++",
    price: "260.000",
    image: "/Centella Air-Fit Suncream Light SPF30 PA++++.png",
    whatitis: "A physical sunscreen with a lightweight, non-whitecast formula gives a natural finish without clogging pores..",
    Benefits: "Calming, SPF",
    ingreditions: "Centella Asiatica Extract, Portulaca Oleracea Extract, Houttuynia Cordata Extract",
    Description: "Daily Light Mineral Sunscreen",
  },
  {
    id: 11,
    name: "Skin Relief Duo",
    price: "544.000",
    image: "/Skin Relief Duo.png",
    whatitis: "The BEST selling duo for gentle exfoliation & skin relief",
    Benefits: "Calming, Soothing",
    ingreditions: "Centella Asiatica Extract, Gluconolactone, Betaine",
    Description: "Best Soothing Duo for Sensitive Skin",
  },
  {
    id: 12,
    name: "Double Cleansing Duo",
    price: "476.000",
    image: "/Double Cleansing Duo.png",
    whatitis: "A double cleansing duo effectively but gently cleanses the face.",
    Benefits: "Calming, Hydrating, Mild exfoliating ",
    ingreditions: "Centella Asiatica Extract, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Helianthus Annuus (Sunflower) Seed Oil, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Sodium Hyaluronate",
    Description: "Effective Double Cleansing Set",
  },
  {
    id: 13,
    name: "Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++",
    price: "189.000",
    image: "/Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++.png",
    whatitis: "A lightweight serum-like sunscreen that hydrates and soothes the skin for a fresh, no white cast finish. Reformulated with Panthenol and extracts of rice, oat, and soybean to help maintain hydration and comfort.",
    Benefits: " Lightweight, UV Protection, Hydrating",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Oryza Sativa (Rice) Extract, Avena Sativa (Oat) Meal Extract, Glycine Max (Soybean) Seed Extract",
    Description: "Hydrating Daily SPF50 Sun Serum",
  },
  {
    id: 14,
    name: "Hyalu-Cica Silky-Fit Sun Stick",
    price: "137.000",
    image: "/Hyalu-Cica Silky-Fit Sun Stick.png",
    whatitis: "A chemical sun stick glides smoothly on the skin and provides instant moisture with a matte and silky finish.",
    Benefits: "Moisturizing, Sebum improvement, UV Protection",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Castanea Crenata (Chestnut) Shell Extract",
    Description: "Moisturizing Matte Finish Sunstick",
  },
  {
    id: 15,
    name: "Hyalu-Cica Sleeping Pack",
    price: "119.000",
    image: "/Hyalu-Cica Sleeping Pack.png",
    whatitis: "A lightweight gel sleeping mask with 5 Hyaluronic acids and Melatonin calms and moisturizes the skin overnight",
    Benefits: " Moisturizing, Calming, Improves Skin Tone ",
    ingreditions: "Centella Asiatica Leaf Water, Hyaluronic Acid, Melatonin, Ceramide NP",
    Description: "Hydrating Overnight Sleeping Mask",
  },
  {
    id: 16,
    name: "Hyalu-Cica Moisture Cream",
    price: "321.000",
    image: "/Hyalu-Cica Moisture Cream.png",
    whatitis: "A lightweight cream with 5 Hyaluronic acids and Hydrolyzed Collagen provides deep hydration that lasts up to 100 hours.",
    Benefits: "Moisturizing, Calming",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Hydrolyzed Collagen",
    Description: "Lightweight Deep moisturizing cream",
  },
  {
    id: 17,
    name: "Hyalu-Cica Blue Serum",
    price: "238.000",
    image: "/Hyalu-Cica Blue Serum.png",
    whatitis: "An all-in-one lightweight serum with Centella, 5 Hyaluronic acids, Ceramide NP, Niacinamide, and Adenosine to hydrate and soothe the skin.",
    Benefits: "Moisturizing, Calming",
    ingreditions: "Centella Asiatica Leaf Water, Hyaluronic Acid, Ceramide NP, Hedera Helix (Ivy) Leaf/Stem Extract",
    Description: "All-in-one Lightweight Hydrating Serum",
  },
  {
    id: 18,
    name: "Hyalu-Cica First Ampoule",
    price: "340.000",
    image: "/Hyalu-Cica First Ampoule.png",
    whatitis: "An all-in-one lightweight serum with Centella, 5 Hyaluronic acids, Ceramide NP, Niacinamide, and Adenosine to hydrate and soothe the skin.",
    Benefits: "Moisturizing, Calming",
    ingreditions: "Centella Asiatica Leaf Water, Hyaluronic Acid, Ceramide NP, Hedera Helix (Ivy) Leaf/Stem Extract",
    Description: "Moisture Boosting Ampoule",
  },
  {
    id: 19,
    name: "Hyalu-Cica Sunsational Kit",
    price: "321.000",
    image: "/Hyalu-Cica Sunsational Kit.png",
    whatitis: "A lightweight serum-like sunscreen that hydrates and soothes the skin for a fresh, no white cast finish. Reformulated with Panthenol and extracts of rice, oat, and soybean to help maintain hydration and comfort.",
    Benefits: "ightweight, UV Protection, Hydrating",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Oryza Sativa (Rice) Extract, Avena Sativa (Oat) Meal Extract, Glycine Max (Soybean) Seed Extract",
    Description: "Hydrating Daily SPF50 Sun Serum",
  },
  {
    id: 20,
    name: "Hyalu-Cica Cloudy Mist",
    price: "321.000",
    image: "/Hyalu-Cica Cloudy Mist.png",
    whatitis: "An ultra-fine mist spray with Green tea and 5 Hyaluronic acid gives instant dewy, glowing skin with a cooling effect",
    Benefits: "Moisturizing, Calming",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Camellia Sinensis Leaf Water, Xylitol, Ceramide NP",
    Description: "Ultra-fine Hydrating Facial Mist",
  },
  {
    id: 21,
    name: "Hyalu-Cica GLOW 1004 DUO",
    price: "375.000",
    image: "/GLOW 1004 DUO.png",
    whatitis: "A simple 2 step duo for a glowing skin with Probio-Cica Intensive Ampoule & Hyalu-Cica Water-Fit Sunserum.",
    Benefits: "Calming, Dewy Skin, SPF",
    ingreditions: "Centella Asiatica Extract, Hyaluronic acid",
    Description: "Duo for Dewy and Glowing skin",
  },
  {
    id: 22,
    name: "Hyalu-Cica Gentle Cleansing Milk",
    price: "321.000",
    image: "/Hyalu-Cica Gentle Cleansing Milk.png",
    whatitis: "A moisturizing gel cleanser for gentle cleansing to recover the skin’s glow.",
    Benefits: "Calming, Spot Correcting, Dullness, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Camellia Sinensis Leaf Water, Xylitol, Ceramide NP",
    Description: "Centella Asiatica Extract, Niacinamide, 3-O-Ethyl Ascorbic Acid, Citric Acid",
  },
  {
    id: 23,
    name: "Hyalu-Cica Jelly-Fit Ampoule Pad",
    price: 240000.0,
    image: "/Hyalu-Cica Jelly-Fit Ampoule Pad.png",
    whatitis: "A jelly-fit ampoule pad that delivers gentle peeling and deep hydration with a hydrogel mask-like effect. It helps relieve inner dryness, refine skin texture, and boost natural radiance for flawless, makeup-ready skin.",
    Benefits: "Hydrating Glow, Smooth Texture, Flawless Base Prep",
    ingreditions: "Madagascar Centella Asiatica Extract, 8 Types of Hyaluronic Acid (Micro-encapsulated), Gluconolactone (PHA), Niacinamide",
    Description: "Hydrating Glow Pad for Sensitive Skin",
  },
  {
    id: 25,
    name: "Tone Brightening Capsule Ampoule",
    price: "153.000",
    image: "/Tone Brightening Capsule Ampoule.png",
    whatitis: "An ampoule for daily use, formulated with Niacinamide, Tranexamic Acid, and encapsulated Madewhite™ to help improve the look of uneven skin tone and dullness for a more radiant-looking complexion.",
    Benefits: "Soothing, Radiance Care, Skin Clarity, Dullness Reduction",
    ingreditions: "Niacinamide, Tranexamic Acid, 3-O-Ethyl Ascorbic Acid, Centella Asiatica Extract, Madecassoside",
    Description: "Gentle Dark spot Correcting Ampoule",
  },
  {
    id: 26,
    name: "Tone Brightening Cleansing Gel Foam",
    price: "214.000",
    image: "/Tone Brightening Cleansing Gel Foam.png",
    whatitis: "A moisturizing gel cleanser for gentle cleansing to recover the skin’s glow.",
    Benefits: "Calming, Spot Correcting, Dullness, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Niacinamide, 3-O-Ethyl Ascorbic Acid, Citric Acid",
    Description: "Moisturizing Gel Cleansing Foam",
  },
  {
    id: 27,
    name: "Tone Brightening Boosting Toner",
    price: "306.000",
    image: "/Tone Brightening Boosting Toner.png",
    whatitis: "A mild exfoliating toner with fruit extracts, Madewhite™, and Niacinamide that gently refines and preps the skin for the next step in your skincare routine.",
    Benefits: "Soothing, Brightening, Skin Clarity, Dullness Reduction",
    ingreditions: "Centella Asiatica Extract, Niacinamide, 3-O-Ethyl Ascorbic Acid (Vitamin C derivative), Madecassoside",
    Description: "Mild Exfoliating Toner for Radiance",
  },
  {
    id: 28,
    name: "Tone Brightening Capsule Cream",
    price: "321.000",
    image: "/Tone Brightening Capsule Cream.png",
    whatitis: "A cream with Niacinamide, Tranexamic Acid, Bisabolol, and encapsulated Madewhite™ that moisturizes and helps improve the look of uneven skin tone for a brighter-looking complexion.",
    Benefits: " Soothing, Radiance Care, Dullness Reduction, Mild Exfoliation",
    ingreditions: "Centella Asiatica Extract, Niacinamide, Tranexamic Acid, Madecassoside, Panthenol, Bisabolol",
    Description: "Skin Tone Balancing Cream",
  },
  {
    id: 29,
    name: "Tone Brightening Tone-Up Sunscreen",
    price: "",
    image: "/Tone Brightening Tone-Up Sunscreen.png",
    whatitis: "A lightweight serum-like sunscreen that hydrates and soothes the skin for a fresh, no white cast finish. Reformulated with Panthenol and extracts of rice, oat, and soybean to help maintain hydration and comfort.",
    Benefits: " Lightweight, UV Protection, Hydrating",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Oryza Sativa (Rice) Extract, Avena Sativa (Oat) Meal Extract, Glycine Max (Soybean) Seed Extract",
    Description: "Hydrating Daily SPF50 Sun Serum",
  },
  {
    id: 30,
    name: "Tone Brightening Dark Spot Ampoule Pad",
    price: "337.000",
    image: "/Tone Brightening Dark Spot Ampoule Pad.png",
    whatitis:
      "Formulated with Niacinamide to help refine pores and visibly even the look of skin tone, Tranexamic Acid to enhance skin texture and help support the skin’s natural barrier, and a Boosting Shot system that helps the skin feel hydrated and refreshed delivering a more even, healthy-looking glow.",
    Benefits: " SPore Refining, Brightening, Radiance Boost, Skin Smoothing",
    ingreditions: "10% Niacinamide, Madagascar Centella Asiatica Extract, Panthenol, Tranexamic Acid, Ascorbyl Glucoside, Hydrolyzed Sponge (Spicules)",
    Description: "A Daily Toning Ampoule for Radiance Boost and Targeted Pore Care",
  },
  {
    id: 31,
    name: "Tone Brightening Set",
    price: "1.074.000",
    image: "/Tone Brightening Set.png",
    whatitis: "The brightening skincare set offers maximum synergistic results.",
    Benefits: " Calming, Spot Correcting, Dullness",
    ingreditions: "Centella Asiatica Extract, Niacinamide, Tranexamic Acid, 3-O-Ethyl Ascorbic Acid, Madecassoside, Citric Acid",
    Description: "Skin Tone Balancing Set",
  },
  {
    id: 32,
    name: "Poremizing Quick Clay Stick Mask",
    price: "337000",
    image: "/Poremizing Quick Clay Stick Mask.png",
    whatitis: "A smooth stick mask with 5 kinds of clays (18% Kaolin) and fine Red bean powder to soak up excess sebum and tightens enlarged pores..",
    Benefits: " Calming, Pore Tightening, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Kaolin, Bentonite, Illite, Montmorillonite, Aloe Barbadensis Leaf Extract",
    Description: "Sebum Soaking Clay Mask Stick",
  },
  {
    id: 33,
    name: "Poremizing Fresh Ampoule",
    price: "162.000",
    image: "/Poremizing Fresh Ampoule.png",
    whatitis: "TA pore-minimizing functional ampoule with Pink mineral salt and 9 Peptides cleanses pores and improves skin elasticity.",
    Benefits: " Calming, Pore Tightening",
    ingreditions: "Centella Asiatica Extract, Mineral Salts, Aloe Barbadensis Leaf Extract",
    Description: "Pore Cleansing & Tightening Ampoule",
  },
  {
    id: 34,
    name: "Poremizing Deep Cleansing Foam",
    price: "214.000",
    image: "/Poremizing Deep Cleansing Foam.png",
    whatitis: "A rich, creamy cleanser with Mineral salts, Kaolin and Papain acts like a magnet to absorb impurities and excess sebum.",
    Benefits: " Calming, Pore Tightening, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Mineral Salts, Kaolin (CI 77004), Papain, Pyrus Malus (Apple) Fruit Extract",
    Description: "Sebum-removing Deep Cleanser",
  },
  {
    id: 35,
    name: "Poremizing Clear Toner",
    price: "300.000",
    image: "/Poremizing Clear Toner.png",
    whatitis: "An exfoliating toner with mineal salts and 4-HAs (AHA, BHA, PHA, LHA) gently cleanses pores and removes dead skin cells.",
    Benefits: " Calming, Pore Tightening",
    ingreditions: "Centella Asiatica Extract, Mineral Salts, Salix Alba (Willow) Bark Extract, Citric Acid, Capryloyl Salicylic Acid, Gluconolactone, Salicylic Acid, Citric Acid",
    Description: "Exfoliating & Sebum Controlling Toner",
  },
  {
    id: 36,
    name: "Poremizing Light Gel Cream",
    price: "321.000",
    image: "/Poremizing Light Gel Cream.png",
    whatitis: "A lightweight gel with Aloe, Niacinamide and Adenosine provides instant cooling and deep hydration to the skin. ",
    Benefits: " Calming, Pore Tightening, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Mineral Salts, Aloe Barbadensis Leaf Extract, Niacinamide, Adenosine, Hamamelis Virginiana (Witch Hazel) Leaf Water, Chamaecyparis Obtusa Water",
    Description: "Lightweight Cooling Gel Cream",
  },
  {
    id: 37,
    name: "Poremizing Velvet Finish Sunscreen",
    price: "290.000",
    image: "/Poremizing Velvet Finish Sunscreen.png",
    whatitis: "TA lightweight serum-like sunscreen that hydrates and soothes the skin for a fresh, no white cast finish. Reformulated with Panthenol and extracts of rice, oat, and soybean to help maintain hydration and comfort.",
    Benefits: " Lightweight, UV Protection, Hydrating",
    ingreditions: "Centella Asiatica Extract, Hyaluronic Acid, Oryza Sativa (Rice) Extract, Avena Sativa (Oat) Meal Extract, Glycine Max (Soybean) Seed Extract",
    Description: "Hydrating Daily SPF50 Sun Serum",
  },
  {
    id: 38,
    name: "Poremizing Perfect Pore Set",
    price: "898.000",
    image: "/Perfect Pore Set.png",
    whatitis: "A complete pore-care solution featuring a 3-step regimen designed to provide mild exfoliation, lightweight hydration, and help improve the appearance of pores.",
    Benefits: " Soothing, Pore care, Mild exfoliation, Lightweight hydration",
    ingreditions: "Centella Asiatica Extract, Aloe Barbadensis Leaf Extract, Kaolin, Mineral Salts",
    Description: "3-Step Care for Smooth and Refined Pores",
  },
  {
    id: 39,
    name: "Tea-Trica Relief Ampoule",
    price: "167.000",
    image: "/Tea-Trica Relief Ampoule.png",
    whatitis: "A non-comedogenic ampoule with Tea tree, Pine tree, and Cypress that helps care for blemish-prone skin and maintain a healthy-looking complexion",
    Benefits: " Calming, Acne, Sensitive",
    ingreditions: "Centella Asiatica Extract, Melaleuca Alternifolia (Tea Tree) Leaf Water, Pinus Palustris Leaf Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Chamaecyparis Obtusa Water",
    Description: "Acne Skin Relief Ampoule",
  },
  {
    id: 40,
    name: "Tea-Trica Spot Cream",
    price: "291.000",
    image: "/Tea-Trica Spot Cream.png",
    whatitis: "A spot cream with 15% Tea tree water and 1% TECA provides immediate relief to acne and blemish areas.",
    Benefits: " Calming, Anti-Aging, Hydrating",
    ingreditions: "Centella Asiatica Extract, Melaleuca Alternifolia (Tea Tree) Leaf Water, TECA(Asiaticoside, Asiatic Acid, Madecassic Acid), Pinus Palustris Leaf Extract, Chamaecyparis Obtusa Water, Calamine",
    Description: "Acne Spot Care Cream",
  },
  {
    id: 41,
    name: "Tea-Trica BHA Foam",
    price: "230.000",
    image: "/Tea-Trica BHA Foam.png",
    whatitis: "A deep cleansing foam alming, Spotwith BHA and Tea tree unclogs pores and exfoliates dead skin cells, leaving a refreshed finish..",
    Benefits: " Calming, Acne, Sensitive, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Melaleuca Alternifolia (Tea Tree) Leaf Water, Salicylic Acid, Pinus Palustris Leaf Extract, Chamaecyparis Obtusa Water",
    Description: "Acne Deep Cleansing Foam",
  },
  {
    id: 42,
    name: "Tea-Trica B5 Cream",
    price: "321.000",
    image: "/Tea-Trica B5 Cream.png",
    whatitis:
      "A soothing and hydrating gel cream formulated with 5% Panthenol, Tea Tree, and Cica Exosome to calm troubled skin and provide lightweight hydration. Perfect for acne-prone and sensitive skin, it absorbs quickly and delivers a refreshing, non-greasy finish.",
    Benefits: " CSoothing, Hydrating",
    ingreditions: "5% Panthenol (Vitamin B5), Tea Tree Extract & Tea Tree Oil, Ceramide NP, Cica Exosome (Centella Asiatica Derived), Centella Asiatica Extract",
    Description: "Soothing Gel Cream with Tea Tree & B5",
  },
  {
    id: 43,
    name: "Tea-Trica Purifying Toner",
    price: "306000",
    image: "/Tea-Trica Purifying Toner.png",
    whatitis: "A Tea tree water toner with Cypress balances oil & sebum, and removes dead skin cells.",
    Benefits: " Calming, Acne, Sensitive",
    ingreditions: "Centella Asiatica Extract, Melaleuca Alternifolia (Tea Tree) Leaf Water, Pinus Palustris Leaf Extract, Chamaecyparis Obtusa Water",
    Description: "Acne Skin Relief Toner",
  },
  {
    id: 44,
    name: "Tea-Trica Soothing Sun Milk",
    price: "321.000",
    image: "/Tea-Trica Soothing Sun Milk.png",
    whatitis:
      "A soothing and hydrating gel cream formulated with 5% Panthenol, Tea Tree, and Cica Exosome to calm troubled skin and provide lightweight hydration. Perfect for acne-prone and sensitive skin, it absorbs quickly and delivers a refreshing, non-greasy finish.",
    Benefits: " Soothing, Hydrating",
    ingreditions: "5% Panthenol (Vitamin B5), Tea Tree Extract & Tea Tree Oil, Ceramide NP, Cica Exosome (Centella Asiatica Derived), Centella Asiatica Extract",
    Description: "Hydrating Daily SPF50 Sun Serum",
  },
  {
    id: 45,
    name: "Tea-Trica Mild Peeling Gel",
    price: "300.000",
    image: "/Tea-Trica Mild Peeling Gel.png",
    whatitis: "A deep cleansing foam with BHA and Tea tree unclogs pores and exfoliates dead skin cells, leaving a refreshed finish.",
    Benefits: " Calming, Acne, Sensitive, Mild exfoliating",
    ingreditions: "Centella Asiatica Extract, Melaleuca Alternifolia (Tea Tree) Leaf Water, Salicylic Acid, Pinus Palustris Leaf Extract, Chamaecyparis Obtusa Water",
    Description: "Lightweight Cooling Gel Cream",
  },
  {
    id: 46,
    name: "Tea-Trica Intensive Calming Set",
    price: "1.075.000",
    image: "/Tea-Trica Intensive Calming Set.png",
    whatitis: "A total care set from the Tea-Trica Line, designed to restore balance. With key ingredients like Tea Tree Extract and Centella Asiatica, it effectively targets blemishes and skin concerns in need of relief.",
    Benefits: " Targeted Spot Care, Deep Hydration",
    ingreditions: "Tea Tree Extract, Centella Asiatica Extract, Pine Tree Complex, Panthenol (B5)",
    Description: "Total Care for Acne-Prone Skin",
  },
  {
    id: 47,
    name: "Probio-Cica Bakuchiol Eye Cream",
    price: "321.000",
    image: "/Probio-Cica Bakuchiol Eye Cream.png",
    whatitis: "A gentle eye cream with fermented Centella and Bakuchiol (vegan retinol) reduces the appearance of fine lines and wrinkles.",
    Benefits: " Calming, Anti-Aging, Hydrating",
    ingreditions: "Lactobacillus/Centella Asiatica Extract Ferment Filtrate, Centella Asiatica Extract, Bakuchiol, Madecassic Acid, Asiaticoside, Asiatic Acid, Ceramide NP",
    Description: "Gentle Anti-wrinkle Eye Cream",
  },
  {
    id: 48,
    name: "Probio-Cica Essence Toner",
    price: "321.000",
    image: "/Probio-Cica Essence Toner.png",
    whatitis: "A rich essence toner with fermented Centella, 5 Hyaluronic acids and Ceramide NP soothes and moisturizes the skin.",
    Benefits: " Calming, Anti-Aging, Hydrating",
    ingreditions: "Lactobacillus/Centella Asiatica Extract Ferment Filtrate, Centella Asiatica Extract, Madecassic Acid, Asiaticoside, Asiatic Acid, Hyaluronic Acid",
    Description: "Rich Essence Soothing Toner ",
  },
  {
    id: 49,
    name: "Probio-Cica Intensive Ampoule",
    price: "337.000",
    image: "/Probio-Cica Intensive Ampoule.png",
    whatitis: "An intensive ampoule with fermented Centella and Ceramides provides soothing hydration, firmness and glow to the skin.",
    Benefits: " Calming, Pore Tightening",
    ingreditions: "Lactobacillus/Centella Asiatica Extract Ferment Filtrate, Centella Asiatica Extract, Madecassic Acid, Asiaticoside, Asiatic Acid, Ceramide NP",
    Description: "Barrier Repairing Soothing Ampoule",
  },
  {
    id: 50,
    name: "Probio-Cica Enrich Cream",
    price: "170.000",
    image: "/Probio-Cica Enrich Cream.png",
    whatitis: "TA thick and smooth cream with fermented Centella, Shea butter and Ceramide NP provides rich moisturization without feeling heavy or sticky. ",
    Benefits: " Calming, Anti-Aging, Hydrating",
    ingreditions: "Lactobacillus/Centella Asiatica Extract Ferment Filtrate, Centella Asiatica Extract, Madecassic Acid, Asiaticoside, Asiatic Acid, Phytosterols",
    Description: "Rich & Buttery Barrier Cream",
  },
  {
    id: 51,
    name: "Probio-Cica GLOW 1004 DUO",
    price: "375.000",
    image: "/Probio-Cica GLOW 1004 DUO.png",
    whatitis: "A simple 2 step duo for a glowing skin with Probio-Cica Intensive Ampoule & Hyalu-Cica Water-Fit Sunserum.",
    Benefits: " Calming, Dewy Skin, SPF",
    ingreditions: "Centella Asiatica Extract, Hyaluronic acid",
    Description: "Duo for Dewy and Glowing skin",
  },
  {
    id: 52,
    name: "Probio-Cica Glow Sun Ampoule",
    price: "306.000",
    image: "/Probio-Cica Glow Sun Ampoule.png",
    whatitis: "A super moisturizing sunscreen with fermented Centella and Panthenol",
    Benefits: " Calming, Anti-Aging, Hydrating",
    ingreditions: "Lactobacillus/Centella Asiatica Extract Ferment Filtrate, Centella Asiatica Extract, TECA, Ceramide NP, Panthenol, Betaine",
    Description: "Sun Ampoule for Damaged Skin Barrier",
  },
  {
    id: 53,
    name: "Probio-Cica Perfect Anti-Aging Routine Set",
    price: "911.000",
    image: "/Perfect Anti-Aging Routine Set.png",
    whatitis:
      "A microbiome-powered skincare set featuring fermented Madagascan Centella Asiatica and Ceramide NP, designed to strengthen hydration, and deliver targeted anti-aging benefits. Perfect for achieving a radiant and healthy glow.",
    Benefits: " Repairing & Strengthening, Calming, Anti-Aging, Hydrating",
    ingreditions: "Lactobacillus/Centella Asiatica Extract Ferment Filtrate, Centella Asiatica Extract, Madecassic Acid, Asiaticoside, Asiatic Acid, Ceramide NP, Hyaluronic Acid, Phytosterols",
    Description: "Complete Glow Routine Set",
  },
];
